services:
  api:
    build: ./Courses
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  web:
    build: ./courses-front
    ports:
      - "3000:3000"
    volumes:
      - ./courses-front:/courses-front