services:
  api:
    image: ansmajid/internship-2:latest 
    ports:
      - "8000:8000"
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  web:
    image: ansmajid/internship-1:latest 
    ports:
      - "3000:3000"